CREATE TABLE public."Contributions" (
    "ContributionId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "FacultyId" uuid NOT NULL,
    "ContributionWindowId" uuid NOT NULL,
    "Subject" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Rating" integer NOT NULL,
    "Status" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedDate" timestamp with time zone,
    "CreatedBy" uuid,
    "SubmittedDate" timestamp with time zone,
    "SubmittedBy" uuid,
    "ReviewedDate" timestamp with time zone,
    "ReviewedBy" uuid,
    "ModifiedDate" timestamp with time zone,
    "ModifiedBy" uuid,
    "CommentedDate" timestamp with time zone,
    "CommentedBy" uuid,
    "CategoryId" uuid,
    CONSTRAINT "Contributions_CategoryId_fkey" FOREIGN KEY ("CategoryId") REFERENCES "Categories"("CategoryId") ON DELETE SET NULL DEFERRABLE,
    CONSTRAINT "Contributions_ContributionWindowId_fkey" FOREIGN KEY ("ContributionWindowId") REFERENCES "ContributionWindows"("ContributionWindowId") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "Contributions_FacultyId_fkey" FOREIGN KEY ("FacultyId") REFERENCES "Faculties"("FacultyId") ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "Contributions_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "Users"("UserId") ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE,
    CONSTRAINT "Contributions_pkey" PRIMARY KEY ("ContributionId")
);
